---
title: "Coffee Game Report"
author: "Elizaveta Oginskaya"
date: "November 6, 2016"
output: html_document
---
```{r}

```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(knitr)
```

## Overview

The year has passed. The macroparameters of the market were as follows:

```{r overview, echo=FALSE}
setwd("C:/Users/Volod/Documents/R/CoffeeGame")
Overview <- read.csv("Reports/Overview.csv", row.names = 1)
ggplot(data = Overview, aes(x = as.factor(Period), y = Demand)) + geom_bar(aes(x = as.factor(Period), y = Demand), stat = 'identity') + geom_bar(aes(x = as.factor(Period), y = Sales), stat = 'identity', fill = "red") + xlab("Period") + ylab("Quantity") + ggtitle("Demand and Sales")

kable(Overview, digits = 2)



```

### Newsletter
Messages on production chain
```{r newsletter, echo=FALSE}
setwd("C:/Users/Volod/Documents/R/CoffeeGame")
if (file.exists("Reports/Newsletter.txt")){
  readLines("Reports/Newsletter.txt")
} else {
  "No news for today"
}
    

```

## Players Results
### Planter Results
```{r planter, echo=FALSE}
setwd("C:/Users/Volod/Documents/R/CoffeeGame")
kable(read.csv("Reports/PlanterReport.csv", row.names = 1), digits = 2)

if (file.exists("Reports/PlanterUnionMessage.txt")){
  readLines("Reports/PlanterUnionMessage.txt")
} else {
  "No messages for today"
}
```

### Roaster Results
```{r roaster, echo=FALSE}
setwd("C:/Users/Volod/Documents/R/CoffeeGame")
kable(read.csv("Reports/RoasterReport.csv", row.names = 1), digits = 2)

if (file.exists("Reports/RoasterUnionMessage.txt")){
  readLines("Reports/RoasterUnionMessage.txt")
} else {
  "No messages for today"
}
```

### Packer Results
```{r packer, echo=FALSE}
setwd("C:/Users/Volod/Documents/R/CoffeeGame")
kable(read.csv("Reports/PackerReport.csv", row.names = 1), digits = 2)

if (file.exists("Reports/PackerUnionMessage.txt")){
  readLines("Reports/PackerUnionMessage.txt")
} else {
  "No messages for today"
}
```

### Retailer Results
```{r retailer, echo=FALSE}
setwd("C:/Users/Volod/Documents/R/CoffeeGame")
kable(read.csv("Reports/RetailerReport.csv", row.names = 1), digits = 2)

if (file.exists("Reports/RetailerUnionMessage.txt")){
  readLines("Reports/RetailerUnionMessage.txt")
} else {
  "No messages for today"
}
```

